apiVersion: v2
appVersion: "1.0"
description: A Helm chart for ia-task-configuration
name: ia-task-configuration
home: https://github.com/hmcts/ia-task-configuration
version: 0.0.3
maintainers:
  - name: HMCTS IA team
dependencies:
  - name: java
    version: 3.4.5
    repository: '@hmctspublic'
